### PR TITLE
New DSL

### PR DESCRIPTION
**Pull request by zilkey**
```js
return page.visit("/")
      .clickLink('New Person')
      .fillIn('First Name', 'Sue')
      .fillIn('Last Name', 'Sylvester')
      .check('Check it out')
      .select('Thirty', {from: 'Age'})
      .clickButton('Submit Me')
      .promise
      .then(function(page){
        // page.$ is a jQuery object representing the document
        expect(page.$("h1").text()).to.equal("It worked")
      })
```

### CODE REVIEW

**Comment by zilkey** [comment]
Hey @lizTheDeveloper - this isn't 100% ready (needs to have better docs / sync the readme), but the basic DSL works.

Thoughts?

**Comment by zilkey** [comment]
It also adds tests, and covers inline JS, form submissions etc...

**Comment by zilkey** [comment]
Also @lizTheDeveloper don't merge this yet.  I can squash things / clean it up.  Just wanted to make sure you saw it early.

**Comment by lizTheDeveloper** [comment]
Looks like there aren't major interface changes so I incremented the minor version to 0.3.4 so I can push and test. I'm going to test upgrading express-drills to the new version, if I end up finding big changes I'll increment the version to 4 and then update express-drills in stages.

**Comment by lizTheDeveloper** [comment]
Looks like the interface did change, going to increment the version number to 0.5.2

**Pull request merged**
